name: C Build and Test

on:
	push:
		branches:
			- dev
	pull_request:
		branches:
			- main

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout code
				uses: actions/checkout@v3

			- name: Set up C Compiler
				run: sudo apt-get update && sudo apt-get install gcc make -y

			- name: Build the project
				run: |
					make

			- name: Run tests
				run: |
					./tests/test_suite
